### ISSUE TITLE
Does not support Mac Catalyst

### ISSUE THREAD

**Issue by huynguyen230892** [abbeycode/UnrarKit#110]
Thanks for making a contribution to UnrarKit! I greatly value issue reports, which help make the library better, and more useful to more people. To help me address your issue, please follow the steps below.

I have a project that need to run on Mac Catalyst. But UnrarKit seen like its cannot run on Mac Catalyst. I tried to use your example but this not working. Can you please take a look. Thanks you.
<img width="1137" alt="Screen Shot 2022-08-16 at 11 33 05" src="https://user-images.githubusercontent.com/32290683/184798519-b7139463-9671-4903-b407-58e24356f85d.png">

**Comment by abbeycode** [comment]
As I stated in Issue #109:

> Now I understand, thanks for clarifying. I'm going to close this as a duplicate of https://github.com/abbeycode/UnrarKit/issues/89, since UnrarKit doesn't support SPM yet. Please feel free to help get SPM integration working and submit a PR. I'd be happy to provide guidance, but I hit a wall when I tried. You can start from my [swiftpm branch](https://github.com/abbeycode/UnrarKit/tree/swiftpm), as mentioned before, where I started but didn't finish it.

It looks like I misunderstood. I see now when I try to check the Mac Catalyst box from the UnrarExample project (even without SPM in the mix) it won't run. I'll see what is going on. Meanwhile I'm going to close this issue as a duplicate and reopen the original one.

**Comment by huynguyen230892** [comment]
Thanks you.
