### ISSUE TITLE
password protected files

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnrarKit#21]
I cant extract password protected files, give me URKErrorCodeUnknown

**Comment by abbeycode** [comment]
Can you send a link to an example of a file that isn't working?

**Comment by amosavian** [comment]
this is a sample file which entire file is protected:
http://cdn.p30download.com/?b=p30dl-software&f=DreamCalc.Professional.v4.9.3_p30download.com.rar
password: www.p30download.com
error for this file is incorrupt header

this is a sample file which a file inside is password protected:
http://www.filedropper.com/fonts-128
password: hello
error no. 21: unspecified error

both don't work

**Comment by abbeycode** [comment]
I'm not able to reproduce. Can you please paste the code you're using?

**Comment by amosavian** [comment]
var unrar = URKArchive.rarArchiveAtURL(filePath);
                    let extractfile = { () -> Void in
                        var error: NSError?
                        unrar.extractFilesTo(destPath, overwrite: false, progress: { (fInfo, percent) -> Void in
                            return
                        }, error: &error)

                        dispatch_async(dispatch_get_main_queue(), {
                            if let error = error {
                                self.delegate?.fileOperationError(error.code, errorDesc: URKErrorCode(rawValue: error.code)!.description)
                            }
                            return
                        });
                    }
                    let myQueue = dispatch_queue_create("com.mousavian.fileoperation", nil);
                    dispatch_async(myQueue, {
                        var error: NSError?
                        unrar.listFileInfo(&error)
                        if let viewController = self.viewController where error?.code == URKErrorCode.MissingPassword.rawValue || unrar.isPasswordProtected() {
                            Utility.UI.askPlain("", withTitle: "Enter Password", placeHolder: "Password", viewController: viewController, defaultText: "", completionHandler: { (text) -> Void in
                                unrar.password = text
                                extractfile()
                            })
                        } else {
                            extractfile()
                        }  
                    })

**Comment by abbeycode** [comment]
Oh, I see what you mean. That's just a log message, and the method still returns the correct value. But your code is a little wrong. The most important thing, is you should be checking return values before considering specific error codes. This is how I would tweak your code (I didn't compile it, but it should be close):

```Swift
var unrar = URKArchive.rarArchiveAtURL(filePath);
let extractFile = { () -> Void in
    var error: NSError?

    if !unrar.extractFilesTo(destPath, overwrite: false, progress: nil, error: &error) {
        dispatch_async(dispatch_get_main_queue(), {
            self.delegate?.fileOperationError(error?.code, errorDesc: URKErrorCode(rawValue: error?.code)!.description)
        }
    });
}
let myQueue = dispatch_queue_create("com.mousavian.fileoperation", nil);
dispatch_async(myQueue, {
    if unrar.isPasswordProtected() {
        Utility.UI.askPlain("", withTitle: "Enter Password", placeHolder: "Password", viewController: self.viewController!, defaultText: "", completionHandler: { (text) -> Void in
            unrar.password = text
            extractfile()
        })
    }
    else {
        extractFile()
    }
})
```

**Comment by abbeycode** [comment]
I did stop that error message though, as it was inappropriate.

**Comment by abbeycode** [comment]
I released a fix to remove the error to CocoaPods. Let me know if you're still having problems.

**Comment by amosavian** [comment]
I still have problem on extracting password protected file with same error.
I use my code for UnzipKit and works like a charm.
Seems your code ignore pasword property, I'm not sure

**Comment by abbeycode** [comment]
Could you please create a fork and add a unit test demonstrating the bug? It would make it a lot easier to see what's going wrong.

**Comment by amosavian** [comment]
did you extracted these 2 files I sent links successfully?

**Comment by abbeycode** [comment]
Yes, I did. I can give you that test case code, if you'd like. When you say you're getting an error, can you explain more what that means?

**Comment by amosavian** [comment]
so it's a problem on my side, maybe old rar library I'm using. it's 5.1 or 5.2 I think
I have to release my app tomorrow and I will postpone this feature. no problem
thanks as I took your time

**Comment by abbeycode** [comment]
No problem, don't worry about it. I'm curious though, when you say you're using an old library, you mean the library you're using to create the archives?

**Comment by amosavian** [comment]
I don't use cocoapods. I inserted rarlib files (cpp files) directly into project and modified them to compile

**Comment by abbeycode** [comment]
Oh, interesting. You don't need to use CocoaPods to get the rarlib files, though. They're embedded in the `Libraries/unrar` directory.
