### ISSUE TITLE
password protection check latency

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnrarKit#24]
hi,
please replace 
int PFCode = RARProcessFile(_rarFile, RAR_SKIP, NULL, NULL);
instead of 
int PFCode = RARProcessFile(_rarFile, RAR_TEST, NULL, NULL);
in (BOOL)isPasswordProtected
to speed up checking

**Comment by abbeycode** [comment]
Good call! I just released a patch in v2.5.1. It should be available from CocoaPods now. :+1:

**Comment by amosavian** [comment]
also it is nice to have a separate method for checkIntegrity via this RAR_TEST option.
also for UnzipKit via CRC check

**Comment by amosavian** [comment]
indeed first I splitted if into two ifs for better performance first after header second after process check but finally I overcame this issue by RAR_SKIP
