### ISSUE TITLE
there are some troubles after i update

### ISSUE THREAD

**Issue by sunyuanyang** [abbeycode/UnrarKit#27]
in the file dll.cpp,Unknow type name 'HANDLE', it cannot run

**Comment by abbeycode** [comment]
Thanks for writing in to report the problem! To help me figure out what's going wrong, can you give me some more information? Specifically, it would help if you could give me a file and the UnrarKit method you're calling on it (ideally some sample code).

**Comment by sunyuanyang** [comment]
<img width="880" alt="2015-08-18 7 44 38" src="https://cloud.githubusercontent.com/assets/5556727/9329134/a4498088-45e1-11e5-94ab-5f168a0505e9.png">

**Comment by abbeycode** [comment]
Oh ok, thanks. Are you using Xcode 7? If so, I'll update to Beta 5 and see if I can reproduce the exception.

**Comment by abbeycode** [comment]
Also, are you building for a Mac or iOS project, and simulator or device?

**Comment by abbeycode** [comment]
I'm not able to reproduce it. I tried with a new Mac app and iOS app, with this Podfile, both of which compiled fine:

    pod "UnrarKit"

`HANDLE` is defined in `dll.hpp`. Do you see it referenced in the `UnrarKit` target's Headers section, as depicted below?

<img width="901" alt="Xcode Pods project settings screenshot" src="https://cloud.githubusercontent.com/assets/1349578/9337303/97af4540-45ac-11e5-8f62-dbaf5e374f1d.png">

If not, what version of CocoaPods are you running? I'm running 0.38.2 (you can tell by running `pod --version`). Also, if your Podfile line for UnrarKit differs from what I put above, could you show me what you're using?

**Comment by sunyuanyang** [comment]
i update pod and it well down. thank u

**Comment by abbeycode** [comment]
I'm glad it's working for you :+1:
