### ISSUE TITLE
 Unknown type name 'class'; did you mean 'Class'?

### ISSUE THREAD

**Issue by khollm** [abbeycode/UnrarKit#28]
Hi ,
when I install UnrarKit in my project (with cocoa pod)  ,
and import UnrarKit through a bridging header : 

#import "UnrarKit/UnrarKit.h"

 I get those error :
for archive.hpp
archive.hpp:4:1: Unknown type name 'class'; did you mean 'Class’?
archive.hpp:5:1: Unknown type name 'class'; did you mean 'Class’?
archive.hpp:6:1: Unknown type name 'class'; did you mean 'Class’?
archive.hpp:23:1: Unknown type name 'class'; did you mean 'Class'?
archive.hpp:23:26: Expected ';' after top level declarator
archive.hpp:23:15: Unknown type name ‘public'

for array.hpp
array.hpp:4:8: Unknown type name 'ErrorHandler'; did you mean 'ProcHandle’?
array.hpp:6:1: Unknown type name ‘template'
array.hpp:6:10: Expected identifier or ‘('
array.hpp:33:1: Unknown type name ‘template'
array.hpp:33:10: Expected identifier or ‘('
array.hpp:42:1: Unknown type name ‘template'
array.hpp:42:10: Expected identifier or ‘('
array.hpp:48:1: Unknown type name ‘template'
array.hpp:48:10: Expected identifier or ‘('
array.hpp:56:1: Unknown type name ‘template'
array.hpp:56:10: Expected identifier or ‘('
array.hpp:65:1: Unknown type name ‘template'

then for my bridging header : 
Too many errors emitted, stopping now

can you help me ?

PS: I don't think the problem come from the code I think the compiler act like the files .hpp are Objective C and not C++ code .

**Comment by abbeycode** [comment]
I'm sorry it's not working for you. To help me figure out what's going on, can you tell me more about your project? Specifically:

1. OS X version
2. Xcode version
3. Target platform (iOS/OS X)
4. Platform version
5. Target type (framework/app)
6. CocoaPods version

Also, could you paste in your Podfile?

**Comment by khollm** [comment]
OS X Yosemite : 10.10.5
Xcode version : 7.1
Target platform : iOS
Platform version : deployment target = 8.0
Target type : app
CocoaPods version : 0.39.0

**Comment by abbeycode** [comment]
Thanks for pointing this out! It should be fixed in v2.5.3. Do a `pod update` and you should be all set. Let me know if you have any other issues.

**Comment by khollm** [comment]
It works . Thanks :)

**Comment by abbeycode** [comment]
:+1:
