### ISSUE TITLE
Examples doesn't work

### ISSUE THREAD

**Issue by gerchicov-bp** [abbeycode/UnrarKit#29]
[!] Unable to find a target named `Demo`
[!] Unable to find a target named `DemoTests`

**Comment by abbeycode** [comment]
Did you open `UnrarKit.xcworkspace`, or `Example/UnrarExample.xcodeproj`? It's meant to be opened in the workspace. Let me know if that works for you.

**Comment by gerchicov-bp** [comment]
I tried to run "pod install" when I'm in ```Example``` directory. This action is usually required by cocoapods. But in this case it seems I need just to download via git and run .xcworkspace file without pod generation, don't I? If so then why do you place a Podfile which doesn't work?

And anyways could you add some details about installation process into the readme file?

**Comment by abbeycode** [comment]
The podfile is there as an example podfile, but is not necessary for the example project. All you should need to do to see the example project is open the workspace.

I'll take a look at the readme, and try to make it clearer.

**Comment by gerchicov-bp** [comment]
Thanks. Yes, I can run it now via .workspace file. The only unclear thing left is if I want to import library files in my own iOS project then may I easily do it via copying sources?

**Comment by abbeycode** [comment]
You can, but it also supports CocoaPods and Carthage, which allow you to receive updates more easily.

**Comment by gerchicov-bp** [comment]
In my case I should replace the existing rar library with a newer one so it is better to import as resources which I could edit any time I need (I mean at least private/protected variables/methods)

**Comment by abbeycode** [comment]
I'm sorry, I don't understand your question. Are you talking about updating UnrarKit, or were you using a different library? If you're talking about forking UnrarKit, you would be able to point Carthage to your own fork, and it should work.

**Comment by gerchicov-bp** [comment]
No, I should replace another library which doesn't work properly with big archives. So I'm trying to test this library first

**Comment by abbeycode** [comment]
Did I answer your question, or are you still unclear?
