### ISSUE TITLE
Add fields for total compressed and uncompressed sizes of archive

### ISSUE THREAD

**Issue by gerchicov-bp** [abbeycode/UnrarKit#32]
It enough complex code but you made it private. It is even not separated into the method

**Comment by abbeycode** [comment]
I don't understand exactly what you're asking for. You can use the following code (copied from `-extractFilesTo:overwrite:progress:error:`) to get an archive's total uncompressed size:

``` objc
    NSError *listError = nil;
    NSArray *fileInfo = [self listFileInfo:&listError];
    NSNumber *totalSize = [fileInfo valueForKeyPath:@"@sum.uncompressedSize"];
```

Are you suggesting I make a property of `URKArchive` with that code?

**Comment by gerchicov-bp** [comment]
Yes, it is better to make this code as a property.
I was confused a little when you get total size and in the same time you get ```uncompressedSize``` via 2 different ways. Now I understand that the first way is to get the whole size at once and the second one is to calculate the common size of the unpacked files

**Comment by abbeycode** [comment]
How are you currently getting the total (compressed) size? I don't remember there being a call for that, either.

**Comment by gerchicov-bp** [comment]
I created a derived class and use it. So now my code looks almost exactly as your one above + some checks from your file

**Comment by abbeycode** [comment]
This has been merged into `master` and will be included in the next release. Let me know if it works for you!
