### ISSUE TITLE
"FileNotFound" problem with Unicode characters in iOS 10.3 with APFS FileSystem

### ISSUE THREAD

**Issue by dttrinh** [abbeycode/UnrarKit#41]
Hi,
After released iOS 10.3 update with the change of FileSystem from HFS+ to APFS, most of filename with Unicode characters are can't unzip. (Before this update, all things are work perfectly)

Based on Apple, to avoid the problem, try to "Use the fileSystemRepresentation property of NSURL objects when creating and opening files with lower-level filesystem APIs such as POSIX open(2), or when storing filenames externally from the filesystem".

I have digged into UnrarKit library and have tried alot but unsuccessful, can you help me with this problem.
Thank you very much!

(Detail problem link: [https://eclecticlight.co/2017/04/06/apfs-is-currently-unusable-with-most-non-english-languages/](url))
(Zip file link: [https://www.dropbox.com/s/hhtoxqixj24dejb/QR%E3%82%B3%E3%83%BC%E3%83%89.zip?dl=0](url))

**Comment by abbeycode** [comment]
Hey, sorry it took me so long to respond (I've got a newborn baby at home), but I'm going to be taking a look at this. I'm going to be addressing UnzipKit's issue 53 first (since it was reported first) but a lot of that work will translate over. Thanks for reporting it!

**Comment by abbeycode** [comment]
This has been addressed (according to @amosavian in abbeycode/UnzipKit#53) by iOS since v10.3.3. Can you please verify if you're still affected by this?
