### ISSUE TITLE
Update to unrar 5.5.5 / fix for VMSF_DELTA memory corruption

### ISSUE THREAD

**Issue by Jegge** [abbeycode/UnrarKit#43]
Hi,

the unrar library used in UnrarKit seems to be vulnerable to the following critical bug: https://bugs.chromium.org/p/project-zero/issues/detail?id=1286&can=1&q=unrar&desc=6 

Could you please update UnrarKit to the latest unrar library?

Thx Jegge

**Comment by abbeycode** [comment]
Thanks for the heads-up! I'll take a look right away.

**Comment by abbeycode** [comment]
This has been merged to master. I'll update the issue and close it out once the update gets pushed to CocoaPods.

**Comment by Jegge** [comment]
Wow that was fast. Thank you a lot! I'll check it out at once.

**Comment by abbeycode** [comment]
The release has been pushed to CocoaPods. Thanks again for pointing this out!

**Comment by aonez** [comment]
Just a typo in the release: 5.5.5 instead of 5.4.5

![screen shot 2017-06-23 at 18 45 48](https://user-images.githubusercontent.com/480163/27491847-3f76d2ce-5844-11e7-9765-df7f81968255.png)

**Comment by abbeycode** [comment]
@aonez Whoops, copy/paste error. Fixed!
