### ISSUE TITLE
UnRar file have password in swift not work

### ISSUE THREAD

**Issue by oceanNg** [abbeycode/UnrarKit#46]
Hi guy. Thank you create and support unbar lib . i'm use lib in swift and i got the problem, i can't extract file have password protected . this is my code
```
var archive : URKArchive?

do {
    archive = try URKArchive(path: files.filePath.path)
    let isPass =  archive?.isPasswordProtected();
    if isPass == true {
        try archive?.extractFiles(to: unzipURL.path, overwrite: true, progress: { (currenyFile, percentLoad) in
            if (percentLoad >= 1.0) {
                self.reloadFilesData()
            }
        })
    }
}
catch{

}

```

18:03:13.870928+0700 TheUnarchiver[50668:720439] [Common] _BSMachError: port 7c0f; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2017-08-15 18:03:13.871261+0700 TheUnarchiver[50668:720439] [Common] _BSMachError: port 7c0f; (os/kern) invalid name (0xf) "Unable to deallocate send right"
 please help me thank !!!

**Comment by abbeycode** [comment]
I cleaned up your code a bit to understand what's going on, but I was confused by the log lines you pasted below it. Are they coming from UnrarKit or TheUnarchiver? Or is that the app you're using with UnrarKit?

Also, what exactly happens when you run your code?

**Comment by abbeycode** [comment]
I'll close this if I don't hear back from you soon
