### ISSUE TITLE
Add UnrarKitResources.bundle to UnrarKit.framework target dependencies

### ISSUE THREAD

**Issue by aonez** [abbeycode/UnrarKit#53]
Since now the framework includes this bundle, it should be necessary to build this first. Adding it to the UnrarKit framework target dependencies should be enough.

Also to UnrarKit iOS framework. I can't build it but i suppose it uses this bundle too.

![screen shot 2017-09-29 at 12 39 42](https://user-images.githubusercontent.com/480163/31012768-527e1604-a513-11e7-904d-6a1d2c95e067.png)

**Comment by abbeycode** [comment]
Good catch!

**Comment by abbeycode** [comment]
This should be addressed by PR #58
