### ISSUE TITLE
Compile with -Weverything flag

### ISSUE THREAD

**Issue by abbeycode** [abbeycode/UnrarKit#56]
This produces a ton of warnings, but the problem is I don't want any warnings reported for the `unrar` library. I can solve this by moving the unrar library into its own static library that'll get compiled in, I think. Then I'll specify `-Weverything` for `UnrarKit`, and `-Wnone` for `unrar`. This makes sense after #55, since it involves changing target configuration around.

- [x] Split `unrar` into its own library, linked into `UnrarKit`
- [x] Specify `-Weverything` for `UnrarKit`
- [x] Fix all warnings produced

**Comment by aonez** [comment]
Those improvements are so cool (the libunrar specifically) 👍🏼
