### ISSUE TITLE
libunrar.a skip install in v2.9-beta5

### ISSUE THREAD

**Issue by aonez** [abbeycode/UnrarKit#62]
When archiving an app using the framework, `libunrar.a` is exported. Skip install flag should be set as `TRUE` on `unrar` target build settings.

Also `dll.hpp` and `raros.hpp` libraries are exported, but I can't figure out how to skip those.

**Comment by abbeycode** [comment]
Can you send me a screenshot of where you're seeing `libunrar.a` that you don't want to? Regarding the headers, `URKArchive.h` imports them, which is why they need to be included in the framework.

**Comment by aonez** [comment]
Sure thing!

![screen shot 2017-10-26 at 14 04 10](https://user-images.githubusercontent.com/480163/32051872-9598a866-ba56-11e7-8d32-a204693a7ddf.png)

Since this happens in the Archive process, I can't sign the `.app`.

**Comment by abbeycode** [comment]
Okay, so that definitely looks wrong for the headers. If you skip install on the libunrar target, that'll probably take care of those too.

Would you mind submitting a PR? That way you can verify using your own build. I use the library through CocoaPods, not Carthage.

**Comment by aonez** [comment]
Here an example project. Just archive the Test scheme to replicate this: [Test.zip](https://github.com/abbeycode/UnrarKit/files/1418288/Test.zip)

> Skip install flag should be set as TRUE on unrar target build settings

This makes the `libunrar.a` disappear, but not the `dll.hpp` and `raros.hpp` 😔

**Comment by abbeycode** [comment]
I'll take a look. And thanks, by the way, for testing it out while it's in beta! Better than turning up an issue like this after it's an official release :)

**Comment by aonez** [comment]
> And thanks, by the way, for testing it out while it's in beta! Better than turning up an issue like this after it's an official release :)

That's what I thought, let's bug @abbeycode before the final release 😛

**Comment by aonez** [comment]
Beta 6 working for me 👏🏼
