### ISSUE TITLE
macOS 10.12 deployment target a must?

### ISSUE THREAD

**Issue by aonez** [abbeycode/UnrarKit#63]
I was able to build it for 10.9.
10.8- does not support NSProgress, so can't build for this one.

**Comment by abbeycode** [comment]
I'm defaulting to 10.12 because it's the cutoff for unified logging. The logging is so much more verbose in this release, but with unified logging consumers of the library can turn it down or off.

**Comment by aonez** [comment]
Makes sense. Thanks!
