### ISSUE TITLE
Some URKLogInfo that might be URKLogDebug

### ISSUE THREAD

**Issue by aonez** [abbeycode/UnrarKit#64]
Should those be `URKLogDebug` instead of `URKLogInfo`?

https://github.com/abbeycode/UnrarKit/blob/a6445be69ad0e16e67bbf46353fc4dbe2f9f3347/Classes/URKArchive.mm#L385

https://github.com/abbeycode/UnrarKit/blob/a6445be69ad0e16e67bbf46353fc4dbe2f9f3347/Classes/URKArchive.mm#L493

https://github.com/abbeycode/UnrarKit/blob/a6445be69ad0e16e67bbf46353fc4dbe2f9f3347/Classes/URKArchive.mm#L601

https://github.com/abbeycode/UnrarKit/blob/a6445be69ad0e16e67bbf46353fc4dbe2f9f3347/Classes/URKArchive.mm#L773

**Comment by abbeycode** [comment]
Thanks for the suggestion! This is what I wast thinking:

https://github.com/abbeycode/UnrarKit/blob/a6445be69ad0e16e67bbf46353fc4dbe2f9f3347/README.md#L201

Perhaps it's too verbose though, since it that particular one happens for almost every RAR operation.

**Comment by aonez** [comment]
In my opinion only errors and uncommon actions should be logged by default. But it's just my preference.

**Comment by abbeycode** [comment]
Good call. I won't release a beta just for this, but it'll make it into the next beta or the final release of v2.9
