### ISSUE TITLE
Fill hasMultipleVolumes on init

### ISSUE THREAD

**Issue by aonez** [abbeycode/UnrarKit#66]
https://github.com/abbeycode/UnrarKit/blob/2861c62e6c44569fb0f129e3b0b27fc9b4a70584/Classes/URKArchive.h#L157

Since the multivolume check is now done on init, I think this property should be filled there.
Also would be useful to have another property like "firstVolumeNotFound", also filled on init.

I can code it if you think like.

**Comment by abbeycode** [comment]
What do you mean by "filling" it? It's a dynamic property, querying the archive's volume info when you call it.

**Comment by aonez** [comment]
I mean remove the dynamic functionality, since whit the init we already do the check.

**Comment by abbeycode** [comment]
That's an interesting idea, thanks. I'll consider it

**Comment by abbeycode** [comment]
@aonez I was looking into this, and I don't see the spot in `init` where we were talking about doing this check. Could you send the line number in URKArchive.mm from the current revision of the v2.9 branch?

**Comment by aonez** [comment]
@abbeycode this is done here:

https://github.com/abbeycode/UnrarKit/blob/4fea60b2b940504e1d14e62720f94158703088c7/Classes/URKArchive.mm#L149-L154

Is that what you asked for? Glad to see beta 10!

**Comment by aonez** [comment]
You're right @abbeycode, the first part of an old convention naming RAR volume will not match that code, anything else will. Maybe it's safer to leave `hasMultipleVolumes` as is now.

**Comment by abbeycode** [comment]
Thanks for the suggestion anyway!
