### ISSUE TITLE
Allowing cancellation directly from extractFiles in middle of a file

### ISSUE THREAD

**Issue by skito** [abbeycode/UnrarKit#74]
Currently cancelation is only supported by the progress object. However in case if we're not extracting data chunks, progress hits only after file is uncompressed. In case we're currently extracting large file 1GB or more, we need to wait the file to be fully extracted before canceling the whole operation. Some times it takes about 30-40sec or more...

**Comment by abbeycode** [comment]
Just to be sure I'm understanding, you're calling `extractFiles` and you can't cancel immediately. It waits until the current file (which may be large) finishes extracting, and then stops the extraction?

If so, I can see that it would be a problem for a larger archive. I'll see if there's a way I can check for cancellation more frequently without changing the way the extraction itself happens.

**Comment by skito** [comment]
Yes, you get it right. As I said in #70 - the current workaround I'm using is to launch `extractFiles` into separate thread and kill the thread on cancellation. It stops immediately - no wait time.

**Comment by abbeycode** [comment]
@skito Can you try out the `cancel-extract` branch? That should allow you to cancel `extractFiles` at any point you wish.

**Comment by abbeycode** [comment]
I've merged this change into the v2.9 branch, and will release a new Beta for you to try shortly.

**Comment by abbeycode** [comment]
This is in v2.9 beta 10. Reopen if this requires any further changes. Enjoy!
