### ISSUE TITLE
Cannot decrease the verbosity of logging

### ISSUE THREAD

**Issue by picasso** [abbeycode/UnrarKit#78]
I cannot  decrease the verbosity of logging...
I followed the instructions and set the `default` level (see the picture), but my console is still full of a huge number of messages that completely interfere with debugging. My archives usually contain 3000-5000 files and the simple operation of getting a list of files leads to several thousand messages in the console.

![screen shot 2018-07-15 at 21 57 27](https://user-images.githubusercontent.com/399395/42755435-6ee3ae3e-88f8-11e8-8819-8a0772ca0920.png)

Anyway, great work and good framework! Thanks!

**Comment by abbeycode** [comment]
What version of macOS are you using? And are you seeing the messages in Xcode's debug output, or the system Console app, or both?

I just set the level to default on my machine while I was developing an app that uses UnrarKit, and it immediately dropped off the verbosity.

**Comment by aonez** [comment]
Maybe relative to #54?

**Comment by picasso** [comment]
macOS - 10.13.6, Xcode - 9.4.1, UnrarKit - 2.9-beta10

I'm seeing the messages in Xcode's debug output and in the system Console app

**Comment by abbeycode** [comment]
As @aonez pointed out above, this is a similar report to his issue #54, in which we realized it's because of the iOS version he was targeting. What's your deployment target OS version?

**Comment by picasso** [comment]
If it was so simple... my deployment target - 10.13

**Comment by abbeycode** [comment]
And just to confirm, you ran:

    sudo log config --mode "level:default" --subsystem com.abbey-code.UnrarKit

And you entered your admin password for `sudo`?

Assuming "yes" to the above, can you send a screenshot of the Console app, with one of those log messages selected?

**Comment by picasso** [comment]
> And just to confirm, you ran:

yes. I posted screenshot with my first message where you could see the current level

>  can you send a screenshot of the Console app, with one of those log messages selected?

there are a lot of messages. Which messages are you interested in?
![screen shot 2018-07-18 at 01 07 13](https://user-images.githubusercontent.com/399395/42850261-02bb778e-8a27-11e8-823d-6d2009cc9e94.png)

**Comment by abbeycode** [comment]
I'm sorry, but I'm at a loss. Have you tried on a different machine? UnrarKit is using the built-in Unified Logging framework now, so I don't know what could be causing this. Maybe try a restart?

**Comment by picasso** [comment]
ok, thanks... well, I'll try different approaches and if I find something, I'll write. 

But by the way, why not let it be managed from the class? I looked at the code - there all the logging functions are made through #define ... why not to add the property to the class and let it change to those who need it. It's still a framework and not an end product ... the developer has the right to manage it

**Comment by abbeycode** [comment]
@picasso have you seen examples of other frameworks that do this, while logging to Apple's logging framework? I'd like to see how they approach it.

To me, one of the advantages of leaving it configured by the system, is the ability to turn up the verbosity as necessary for customers who are experiencing problems. If you turn it off in code (as in @aonez's patch), you lose that capability.

**Comment by abbeycode** [comment]
Also, check out [this doc page](https://developer.apple.com/documentation/os/logging#2878594) - it looks like you can customize with plist files also.

**Comment by picasso** [comment]
@aonez  thanks for your efforts, but my current problem that these log messages prevent me to work in DEBUG mode. I receive a thousand messages (because I work with large archives) and among these messages I have to search my own debugging messages. Anyway it's just inconvinient but not fatal :) The framework works, just my work is not so relaxed..

**Comment by picasso** [comment]
@abbeycode I already tried plist but with the same result. I think that this is the consequence of some configurations on my computer... I've lived with him for more than 6 years, maybe something accumulated over time somewhere in the Library...

> To me, one of the advantages of leaving it configured by the system, is the ability to turn up the verbosity as necessary for customers who are experiencing problems. If you turn it off in code (as in @aonez's patch), you lose that capability.

I really do not think there will be a customer who examines the documentation, finds the necessary `command`, can run `Terminal`, knows what `sudo` is, understands which framework is used in his application and can enable logging. And even if he does all these starnge things - what next? How he will be able to fix bugs?

but this is just my opinion, not more than

**Comment by abbeycode** [comment]
@picasso There are easier ways to get the logs from a user (such as a sysdiagnose), but regardless, I do think @aonez's suggestion can help you at design time too - just remove his conditional compilation  flag and turn off all UnrarKit logging until and unless you need it.

**Comment by picasso** [comment]
> just remove his conditional compilation flag and turn off all UnrarKit logging
@abbeycode you are right... I'm always reluctant to change anything in the framework, but here there is only a possible solution.
