### ISSUE TITLE
Realm and UnrarKit both have a list.hpp header

### ISSUE THREAD

**Issue by zhouluyao2020** [abbeycode/UnrarKit#90]
i use "pod Realm" in project,botn UnrarKit and Realm contains list.hpp file,#include "list.hpp" in Realm Invoked UnrarKit,Can you rename for list.hpp.

**Comment by abbeycode** [comment]
Unfortunately, list.hpp is part of the rarlib source code, which I don't modify directly. I keep it as-is. Can you please show me exactly the error you're seeing?

**Comment by zhouluyao2020** [comment]
in Xcode,new Project ,use cocoapod add pod 'UnrarKit', '~> 2.7.1' ,pod 'RealmSwift', '3.17.3',you will see the error

**Comment by abbeycode** [comment]
I've made a patch in the `issue90` branch, if you'd like to test that out. If it works, I'll consider merging it in, but I'm a little hesitant to arbitrarily remove a file the library ships with. Have you tried asking Realm whether they'd consider naming theirs something less generic, as it appears that for them it's not an external dependency but rather a file they wrote and maintain?

**Comment by abbeycode** [comment]
@zhouluyao2020 I'm going to close this now. If it's still an issue for you, reopen it when you're ready to discuss whether the `issue90` branch fixes this for you.

**Comment by syedecryptr** [comment]
I am also facing the same issue please considerr merging issue90 branch.

**Comment by abbeycode** [comment]
@syedecryptr Thanks for reaching out! Did you try using `issue90` and verify the items below? If so, I'm happy to merge into the v2.10 branch which I'm hoping to release soon-ish.

# The library works as expected
# UnrarKit still performs as expected

**Comment by zhouluyao2020** [comment]
I change the list.hpp and list.cpp filename to listForUnrar.hpp and   listForUnrar.cpp in my local pod project,it's work for me.awesome library,hope naming the filename add prefix  less generic.

**Comment by abbeycode** [comment]
@zhouluyao2020 As I mentioned to @syedecryptr above, if you'd like to verify the two items I listed in the `issue90` branch, I can merge it in for the next release. It basically looks like UnrarKit doesn't need the `rar` library's list.hpp, so I'm able to exclude it altogether (even better than a prefix!).

**Comment by syedecryptr** [comment]
I installed the issue90 branch with the help of this [answer](https://stackoverflow.com/a/39930762) and :
1.  The library works as expected. 
2. I was able to unrar all three kinds of files RAR, RAR5, and RAR with a password.

To be more exact I was working on a plugin for flutter using this library [unrar_file](https://pub.dev/packages/unrar_file) and it was working as expected but when I tried it in my application it was failing because several other plugins were dependent on Realm and this issue was occurring. I then used the issue90 branch and it started working perfectly fine.

**Comment by kunkunbobo** [comment]
> @zhouluyao2020 As I mentioned to @syedecryptr above, if you'd like to verify the two items I listed in the `issue90` branch, I can merge it in for the next release. It basically looks like UnrarKit doesn't need the `rar` library's list.hpp, so I'm able to exclude it altogether (even better than a prefix!).

I have this issu too,but use 2.10-beta5 is OK,can you release  2.10 official version faster?

**Comment by abbeycode** [comment]
Thanks to everyone who wrote in about this one. I’ve merged in the fix, for inclusion in v2.11. I’m trying to get a beta of v2.11 out soon to CocoaPods and Carthage.
